networks:
  inception-network:
    name: inception-network
    driver: bridge

volumes:
  nginx-data:
    driver: local
    driver_opts:
      type: none
      device: /home/user4/data/nginx
      o: bind

  wordpress-data:
    driver: local
    driver_opts:
      type: none
      device: /home/user4/data/wordpress
      o: bind

  mariadb-data:
    driver: local
    driver_opts:
      type: none
      device: /home/user4/data/mariadb
      o: bind

services:
  nginx:
    image: nginx-image
    build:
      context: ./requirements/nginx
    container_name: nginx_container
    volumes:
      - wordpress-data:/usr/share/nginx/html
    networks:
      - inception-network
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: always

  wordpress:
    image: wordpress-image
    build:
      context: ./requirements/wordpress
    container_name: wordpress_container
    environment:
      WORDPRESS_DB_HOST: ${MARIADB_HOST}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - inception-network
    expose:
      - "9000"
    depends_on:
      - mariadb
    restart: always

  mariadb:
    image: mariadb-image
    build:
      context: ./requirements/mariadb
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - inception-network
    expose:
      - "3306"
    restart: always

